apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  DB_PASS: cGFzc3dvcmQ=  # password (base64 encoded)
  JWT_SECRET: c2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # secret-key-change-in-production (base64 encoded)