apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: user-service
        env:
        - name: NODE_ENV
          value: "development"
        resources:
          limits:
            cpu: 300m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi